# Replace with the actual resource name of your EKS cluster.
# For example, if you defined your EKS cluster like resource "aws_eks_cluster" "main", use aws_eks_cluster.main
# variable "eks_cluster_resource_name" {
#   description = "The name of the Terraform resource block that created the EKS cluster"
#   type        = string
#   default     = "aws_eks_cluster.example_eks" 
# }

# Add the Helm repository for the AWS Load Balancer Controller
# resource "helm_repository" "aws_load_balancer_controller" {
#   name = "aws-load-balancer-controller"
#   url  = "https://aws.github.io/eks-charts"
# }

# --- FIXED HELM RELEASE FOR AWS LOAD BALANCER CONTROLLER ---
resource "helm_release" "aws_load_balancer_controller" {
  name             = "aws-load-balancer-controller"
  repository       = "https://aws.github.io/eks-charts"
  chart            = "aws-load-balancer-controller"
  namespace        = "kube-system"
  version          = "1.4.0" # Use a stable and compatible version

  # Critical Values for EKS deployment
  set {
    name  = "clusterName"
    value = var.cluster_name
  }

  set {
    name  = "serviceAccount.create"
    value = "true"
  }

  set {
    name  = "serviceAccount.name"
    value = "aws-load-balancer-controller"
  }

  # --- CRITICAL FIX: DEPENDS_ON ---
  # Ensures this resource only runs *after* the EKS cluster and its Node Groups 
  # are fully created and the providers can connect.
  depends_on = [
    data.aws_eks_cluster.eks_cluster_data,
    data.aws_eks_cluster_auth.eks_cluster_auth_data,
    # Add your EKS cluster resource name here, e.g., aws_eks_cluster.main
    #local.eks_cluster_resource_name
    module.eks
  ]
}














# # Fetch a temporary authentication token for the Kubernetes provider
# # This data source is crucial for authenticating to the EKS cluster API.
# data "aws_eks_cluster_auth" "this" {
#   name = module.eks.cluster_name
# }

# # --- Kubernetes Provider Configuration ---
# # This block tells Terraform how to talk to the EKS control plane.

# provider "kubernetes" {
#   # EKS API Endpoint
#   host                   = module.eks.cluster_endpoint
#   # Base64 encoded certificate authority data
#   cluster_ca_certificate = base64decode(module.eks.cluster_certificate_authority_data)
#   # Temporary token generated by aws_eks_cluster_auth
#   token                  = data.aws_eks_cluster_auth.this.token
# }

# # --- Helm Provider Configuration ---
# # Note: The Helm provider implicitly uses the 'kubernetes' provider defined above.

# # If you need to explicitly define the Helm provider (only necessary if using aliases)
# # provider "helm" {
# #   kubernetes {
# #     host                   = module.eks.cluster_endpoint
# #     cluster_ca_certificate = base64decode(module.eks.cluster_certificate_authority_data)
# #     token                  = data.aws_eks_cluster_auth.this.token
# #   }
# # }


# # --- AWS Load Balancer Controller Helm Release ---

# resource "helm_release" "aws_load_balancer_controller" {
#   repository = "https://aws.github.io/eks-charts"
#   chart      = "aws-load-balancer-controller"
#   name       = "aws-load-balancer-controller"
#   namespace  = "kube-system"
#   wait       = true

#   set {
#     name  = "clusterName"
#     value = var.cluster_name
#   }
  
#   set {
#     name  = "serviceAccount.annotations.eks\\.amazonaws\\.com/role-arn"
#     value = aws_iam_role.alb_controller_irsa.arn
#   }
  
#   # 2. Setting the Service Account Annotation (IRSA)
#   # This uses double backslashes to ensure the Helm chart receives the correctly escaped name.

  
#   # 1. Setting clusterName
#   #set {
#    # name  = "clusterName"
#    # value = var.cluster_name
#   #}
  
#   # 2. Setting the Service Account Annotation (IRSA)
#   # This uses double backslashes to ensure the Helm chart receives the correctly escaped name.
#   #set {
#   #  name  = "serviceAccount.annotations.eks\\.amazonaws\\.com/role-arn"
#    # value = aws_iam_role.alb_controller_irsa.arn
#   #}
# }